apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-db-migrate"
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-job
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-db-migrate"
      labels:
        app: {{ .Release.Name }}
        component: {{ .Release.Name }}-job
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      automountServiceAccountToken: false
      restartPolicy: Never
      containers:
      - name: {{ .Release.Name }}-db-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | replace "#" ""}}"
        command: ["/bin/sh", "-c", "python manage.py migrate users && python manage.py migrate contenttypes && python manage.py migrate auth && python manage.py migrate admin && python manage.py migrate sites && python manage.py migrate sessions"]
        env:
          - name: DJANGO_SETTINGS_MODULE
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: djangoSettingsModule
          - name: VC_ADMIN_DEBUG
            value: "off"
          - name: VC_ADMIN_STATIC_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: staticUrl
          - name: VC_ADMIN_PRIVATE_STREAMS_RPC_ADDR
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: privateStreamsRpcAddr
          - name: VC_ADMIN_BROKER_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: brokerUrl
          - name: VC_ADMIN_CELERY_RESULT_BACKEND
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: celeryResultBackend
          - name: VC_ADMIN_SENTRY_DSN
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: sentryDsn
          - name: VC_ADMIN_EMAIL_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: emailHost
          - name: VC_ADMIN_EMAIL_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: emailHost
          - name: VC_ADMIN_DEFAULT_FROM_EMAIL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: defaultFromEmail
          - name: VC_ADMIN_VALIDATION_EMAILS
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: validationEmails
          - name: VC_ADMIN_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: secretKey
          - name: VC_ADMIN_EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: emailPassword
          - name: VC_ADMIN_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: databaseUrl
          - name: VC_ADMIN_STREAM_MANAGER_CONTRACT_ADDR
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: streamManagerContractAddr
          - name: VC_ADMIN_SYMPHONY_KEY_FILE
            value: "/etc/secrets/symphonyKey"
          - name: VC_ADMIN_SYMPHONY_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: symphonyKey
          - name: VC_ADMIN_SYMPHONY_ADDR
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: symphonyAddr
          - name: VC_ADMIN_SYMPHONY_OAUTH2_CLIENTID
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: symphonyOauth2Clientid