apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-db-migrate"
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-job
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-db-migrate"
      labels:
        app: {{ .Release.Name }}
        component: {{ .Release.Name }}-job
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      automountServiceAccountToken: false
      restartPolicy: Never
      containers:
      - name: {{ .Release.Name }}-db-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | replace "#" ""}}"
        command: ["/bin/sh", "-c", "python manage.py migrate contenttypes && python manage.py migrate auth && python manage.py migrate admin && python manage.py migrate sites && python manage.py migrate sessions"]
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: "project.settings.migrate"
          - name: VC_ADMIN_DEBUG
            value: "off"
          - name: VC_ADMIN_STATIC_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: staticUrl
          - name: VC_ADMIN_PRIVATE_STREAMS_RPC_ADDR
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: privateStreamsRpcAddr
          - name: VC_ADMIN_SENTRY_DSN
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: sentryDsn
          - name: VC_ADMIN_FAUCET_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: faucetUrl
          - name: VC_ADMIN_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: secretKey
          - name: VC_ADMIN_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: databaseUrl
          - name: VC_ADMIN_STREAM_MANAGER_CONTRACT_ADDR
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: streamManagerContractAddr
          - name: VC_ADMIN_RPC_NODE_HTTP_ADDR
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: rpcNodeHttpAddr