# Generated by Django 2.2 on 2019-12-16 08:12

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_ping_at', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('NEW', 'NEW'), ('OFFLINE', 'OFFLINE'), ('IDLE', 'IDLE'), ('BUSY', 'BUSY')], max_length=100, null=True)),
                ('current_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Public Key')),
                ('tags', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('system_info', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Miner',
                'verbose_name_plural': 'Miners',
                'db_table': 'miners',
                'managed': False,
            },
        ),
    ]
