env:
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP

  - name: DJANGO_SETTINGS_MODULE
    valueFrom:
      configMapKeyRef:
        name: {{ .Release.Name }}
        key: djangoSettingsModule
  - name: VC_ADMIN_DEBUG
    value: "off"
  - name: VC_ADMIN_STATIC_URL
    valueFrom:
      configMapKeyRef:
        name: {{ .Release.Name }}
        key: staticUrl
  - name: VC_ADMIN_SENTRY_DSN
    valueFrom:
      configMapKeyRef:
        name: {{ .Release.Name }}
        key: sentryDsn
  - name: VC_ADMIN_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: {{ .Release.Name }}
        key: secretKey
  - name: VC_ADMIN_DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: {{ .Release.Name }}
        key: databaseUrl
