apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-proxy
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.proxyService.type }}
  ports:
    - port: {{ .Values.proxyService.externalPort }}
      targetPort: {{ .Values.proxyService.internalPort }}
      protocol: TCP
      name: {{ .Values.proxyService.name }}
  selector:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-proxy