apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-proxy
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Release.Name }}-proxy
  minReplicas: {{ .Values.proxyAutoscaler.minCount }}
  maxReplicas: {{ .Values.proxyAutoscaler.maxCount }}
{{ toYaml .Values.proxyAutoscaler.targets | indent 2 }}
