{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - backend:
          name: {{ .Chart.Name }}
          port:
            number: {{ .Values.service.ports.http }}
        path: /imsgx72bs1pxd72mxs
      - backend:
          name: {{ .Chart.Name }}
          port:
            number: {{ .Values.service.ports.http }}
        path: /imsgx72bs1pxd72mxs/assets
    host: {{ .Values.ingress.host }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.secret }}
{{- end -}}
