---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
      protocol: TCP
      name: http-backend
    - port: {{ .Values.static.service.ports.http }}
      targetPort: {{ .Values.static.service.ports.http }}
      protocol: TCP
      name: http-static
  selector:
    app: {{ .Chart.Name }}
    component: backend
