apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-static
  labels:
    app: {{ .Release.Name }}-static
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.staticConfig | indent 2 }}