# Generated by Django 2.2 on 2019-12-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('CREATE INDEX users_idx ON users (id);')
    ]
