kind: pipeline
type: kubernetes
name: release

steps:
  - name: build backend
    image: plugins/docker
    settings:
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      registry: registry.videocoin.net
      repo: registry.videocoin.net/cloud/admin
      tags:
        - ${DRONE_COMMIT_SHA}

  - name: build static
    image: plugins/docker
    settings:
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      registry: registry.videocoin.net
      repo: registry.videocoin.net/cloud/admin-static
      dockerfile: Dockerfile.static
      tags:
        - ${DRONE_COMMIT_SHA}

trigger:
  event:
  - push
  - pull_request


---
kind: pipeline
type: kubernetes
name: deploy-dev

steps:
 - name: deploy
   image: devth/helm:v3.1.1
   environment:
      KUBE_CONFIG:
        from_secret: dev_kube_config
   commands:
     - echo $KUBE_CONFIG | base64 -d > kube.config
     - helm --kubeconfig=kube.config upgrade -i --wait --set image.tag=${DRONE_COMMIT_SHA} -n console admin ./deploy/helm

trigger:
  event:
  - push
  - pull_request
  branch:
  - infra
  - drone

depends_on:
  - release
