defaults: &defaults
  working_directory: /go/src/github.com/VideoCoin/adminpanel
  docker:
    - image: golang:latest
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: install requirements
          command: |
            apt update && apt upgrade -y
      - checkout
      - run:
          name: deps
          command: |
            make deps
      - run:
          name: build
          command: |
            make build
workflows:
  version: 2
  test_build_upload:
    jobs:
      - checkout
      - build:
