# Generated by Django 2.2 on 2019-12-16 08:12

from django.db import migrations, models
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
