replicasCount: 1
maxUnavailableCount: 0

serviceAccount:
  name: default

image:
  repository: registry.videocoin.net/cloud/admin
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets:
  - name: regcred

service:
  ports:
    http: 8000

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi

autoscaler:
  minCount: 1
  maxCount: 3
  targets:
    targetCPUUtilizationPercentage: 70

worker:
  replicasCount: 1
  maxUnavailableCount: 0
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 128Mi

workerbeat:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi

static:
  image:
    repository: registry.videocoin.net/cloud/admin-static
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets:
    - name: regcred
  service:
    ports:
      http: 80
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 16Mi
  config:
    nginx.conf: |
      events {
          worker_connections 1024;
      }

      http {
          include /etc/nginx/mime.types;

          server {
              listen 80;

              server_name localhost;

              root /usr/share/nginx/html;

              location / {
                  try_files $uri /index.html;
              }
          }
      }

config:
  DJANGO_SETTINGS_MODULE: "project.settings.staging"
  DEBUG: "off"
  STATIC_URL: "/imsgx72bs1pxd72mxs/assets/"
  PRIVATE_STREAMS_RPC_ADDR: "streams.console.svc.cluster.local:5102"
  BROKER_URL: "redis://:redis@redis-master.redis.svc.cluster.local:6379/6"
  CELERY_RESULT_BACKEND: "redis://:redis@redis-master.redis.svc.cluster.local:6379/7"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_USER: "monitoring@liveplanet.net"
  DEFAULT_FROM_EMAIL: "monitoring@liveplanet.net"
  VALIDATION_EMAILS: "adidenko@liveplanet.net;asysoev@liveplanet.net;dmitry@liveplanet.net"
  SYMPHONY_ADDR: "https://symphony.dev.videocoin.net"
  SYMPHONY_OAUTH2_CLIENTID: "47928468404-hfuqhrb6lhtv9sem30rkjc1djcrlpt4v.apps.googleusercontent.com"

ingress:
  enabled: true
  host: adm.dev.videocoin.net
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
    kubernetes.io/ingress.class: nginx
  secret: tls-cert-console-admin

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "console-admin"
  vault.hashicorp.com/agent-inject-secret-common: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/common/config"
  vault.hashicorp.com/agent-inject-secret-config: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/admin/config"
  vault.hashicorp.com/agent-inject-template-common: |
    {{ with secret "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/common/config" }}{{ range $k, $v := .Data }}
    export {{ $k }}='{{ $v }}'
    {{ end }}{{ end }}
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/admin/config" }}{{ range $k, $v := .Data }}
    export {{ $k }}='{{ $v }}'
    {{ end }}{{ end }}
