replicaCount: 1
proxyReplicaCount: 1
workerReplicaCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/admin
  tag: latest
  pullPolicy: Always
proxyImage:
  repository: nginx
  tag: 1.11.10-alpine
  pullPolicy: IfNotPresent
staticImage:
  repository: registry.videocoin.net/cloud/admin-static
  tag: latest
  pullPolicy: Always

service:
  name: http
  type: ClusterIP
  externalPort: 80
  internalPort: 8000
proxyService:
  name: http
  type: NodePort
  externalPort: 80
  internalPort: 80
staticService:
  name: http
  type: NodePort
  externalPort: 80
  internalPort: 80

db:
  connectionName:
  port: 3306

admin:
  email:
  password:

autoscaler:
  minCount: 3
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70
proxyAutoscaler:
  minCount: 3
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

config:
  djangoSettingsModule: "project.settings.staging"
  staticUrl: "/imsgx72bs1pxd72mxs/assets/"
  privateStreamsRpcAddr: "streams:5102"
  brokerUrl: "redis://:redis@redis-master:6379/6"
  celeryResultBackend: "redis://:redis@redis-master:6379/7"
  sentryDsn: ""
  emailUser: "monitoring@liveplanet.net"
  emailHost: "smtp.gmail.com"
  defaultFromEmail: "monitoring@liveplanet.net"
  validationEmails: "adidenko@liveplanet.net;asysoev@liveplanet.net;dmitry@liveplanet.net"
  symphonyAddr: "https://symphony.dev.videocoin.net"
  symphonyOauth2Clientid: "47928468404-hfuqhrb6lhtv9sem30rkjc1djcrlpt4v.apps.googleusercontent.com"

secrets:
  emailPassword: "akZhc3dWMkJlc1g2YUghZ256QU1oWnhKNzl2c2R1QnZOd2RranA="
  symphonyKey: "e1widHlwZVwiOiBcInNlcnZpY2VfYWNjb3VudFwiLFwicHJvamVjdF9pZFwiOiBcInZpZGVvY29pbi1uZXR3b3JrXCIsXCJwcml2YXRlX2tleV9pZFwiOiBcImU5MTM4MWM2ZGJhMmU4NzgwOGVjMzAzYWYxOWNhMzFkNDA2ZTQ4ZmVcIixcInByaXZhdGVfa2V5XCI6IFwiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXFxuTUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0FnRUFBb0lCQVFEUUpRL0N1aVU3Z241VVxcbjhhVlJCQWZGbjg3NENIRmxGRWc5bXZiL2F5YTlYRGl1YXh2Mmk3VG5ETG9CYjkvSDVuL2FYR3pVRlc0cmVyVDdcXG5HUjVhSmJtL25GUTJZbExCR0J3eGR6REdxcm4vempXaitZZFh5WlU2SUk3N21QdDdBczcrVHJaYktaaDZuVi9mXFxuMGZOTkk5aXIyRndlNDNFQmluV08wZTZlTHpBVnQ1WU1OTkhOdHl0WmVVNTJoUG1UOXJ1UnNEMzB6RmJqV1lwMFxcblh5L2tka1dPdmRzeTdwS0d0TmdFUTZmNzA4dXlIUHgzeHlMSlBURkdZUGllSlFlSVRDUUVPZ3ZVR0phUjhwVDdcXG5NdW1KejZFV0d3cm5vMWwrcjVmZmhBSm8zSjZQZE5ISDdLRDZjblp5eG96czBkNzRjQlY4eDFORkovcGtrR3VDXFxuOEV4TStrbWZBZ01CQUFFQ2dnRUFPY05uUmMrWjRKTjgwcjhDOVdKTWM5dy9PRmREZk4wdGxTY3B6OFZoU1dETFxcbi9CK09jWlBnM3RRSjFMZEMzN3VJbE1WY2tGam9LNW5RbXZTa0Z6bHIvSkI2VUdObCt0OWhoNXEveHdwL05zMzNcXG4xZXM4VTdFR1FFemowVS9wem4vL2lOUzRSOEZaNXdGQXA2RWd4N0lnZ2NRNEFIeDNFb25seVA1YW5ieVR1QnFyXFxuN1daOEpaZ1JHN2tvb1M2emwvV2ZqYk53Wm1pSzlvMVdWM1N4dHJqSmhsVUN0d2FKMTh0VnNzQXRYN0YrRzlzVFxcbmxoWG5UNzNYdjVvSFBOMFZxcFFmU2lOMDZsYitJVlRBc2REYmFWNEhWR1FyYXBCOC9rT21QcStQRkx6Z0JGSnNcXG5wcmptYTBRbkp2MnI5bzQvOU0xWTBKa0NSYzhCVHhCd0NaSDRqZ2s0U1FLQmdRRDBXNkxGUENqZVpuQWpqRzNCXFxuQnRZY01OajdHdHNuaVV6OEJKVFBEVnRzaUMrcTgvRmtySkdHK3p1U2Q3Q3RnVzY0ZE5MRTVjSy95MUIvYk5ld1xcbmVPSFJlTGhYbWlBNEZFSlgxdDdtR1kxQVpFZm9HYkpvQUVIVVZPVHp6Q2NCdTJ6RE1ITjA5QXNPOHlhbjVxbnlcXG5wZ045SklzZmdWak5yUHVQVDlaa3VaY2NCd0tCZ1FEYUQ3NXhZSDRLV0xpaTJ0ZVlaWllGR3VuVFQ3YW5SSHNpXFxueEs0VHI1OXZ1enlEbllZeFg1UkYra29FK3Fta0tDWDNKSFJpdzRSNDZBaWtnVFk0Y1loRFdveForREk2TDNqU1xcbnBScnBuUmtUdnBQSEFBWUZUd3FQRWVsbWtQL0h5TUg3WS9oUW5Ma3AzNTluRW9hQkJCRnV6U0t4SnlUWUc1SXlcXG56TFZHdjNDdnFRS0JnRTZBT2RSZk5VbnRZczBveWdHZTdwM3oyMkVnQ1pPeitqVmtTMklSQ25QZGRHTFpKNDJPXFxuR3RwZ1Q0MElRb3dhN3JUM1l0YTZjVXdvUnQ0STIybm9DN085c29zQ0NxTzVibTdGcXFvRlAybVdUYnQwdGVuUFxcblcxYVpSMHhESTZ6Y3gxNFZiS0gvM0tXYTI2cEk0Z1AvN1ZNQXNHa1lwcXk4aTd4SWk3bWtIYlYxQW9HQkFNanNcXG5MTXdHM3R2bHQrckd2bFI3ZGVtcVRMMForL0RQbHE0SWoyVXdNelllVGJud0VVKzVBOFFleE1rbHRkMjk2STE2XFxuRjR0UkgrVFAxL2JMNEF2T0FJSWZFcWRybTh3bEphemgySlJjM2xobEI0RWJNbkQ5elhyYVJEYnZiOTdEeW9rNlxcbktma05EMGZYOXVaZ0dYTVRMb1RybXdXa1RieWFXdkZYMGNnb2FVcFJBb0dCQUlmU29jVXU4TlFlVksvSVJSRWFcXG53MEkyeDZkK0MwWkN5MmxpNjBGRmR1MFUrd1hCUDUwSlFMVXd6bmF1dlJiVytpR3I0MjJla3I4dHJobzFEek5BXFxuNmVYb1RNNTJkT05ick01dHJjajdRODZhOUZoY0VBV0tQeERKZGd0UXc4MnpqN2NFRlhUckM1MUMrYU9XY0F6elxcblhScjVTQnFaSmdRdGs5c3lMUjBzUWJkNVxcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cXG5cIixcImNsaWVudF9lbWFpbFwiOiBcImNsb3VkLWRldi1ycGNAdmlkZW9jb2luLW5ldHdvcmsuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb21cIixcImNsaWVudF9pZFwiOiBcIjExMDAyNzcyNTI4NzAyMDk5MDM4NVwiLFwiYXV0aF91cmlcIjogXCJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aFwiLFwidG9rZW5fdXJpXCI6IFwiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW5cIixcImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybFwiOiBcImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0c1wiLFwiY2xpZW50X3g1MDlfY2VydF91cmxcIjogXCJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2Nsb3VkLWRldi1ycGMlNDB2aWRlb2NvaW4tbmV0d29yay5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbVwifQ=="
  streamManagerContractAddr: "MHgzYzI2QWVBMGJhN2Y2ZTZCMGJjQUE4NEMzMzQ2MzRFNzk5NzRiYzMz"
  databaseUrl: "bXlzcWw6Ly9yb290OlpxQURlY1hzdzMxMkBteXNxbC5jb25zb2xlLnN2Yy5jbHVzdGVyLmxvY2FsOjMzMDYvY29uc29sZT9jaGFyc2V0PXV0Zjg="
  secretKey: "akZhc3dWMkJlc1g2YUghZ256QU1oWnhKNzl2c2R1QnZOd2RranA="

staticConfig:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;

        server {
            listen 80;

            server_name localhost;

            root /usr/share/nginx/html;

            location / {
                try_files $uri /index.html;
            }
        }
    }
