# Generated by Django 2.2 on 2019-12-16 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
                ('kind', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Withdraw')], null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'New'), (2, 'Pending native'), (3, 'Executed_native'), (4, 'Pending erc'), (5, 'Completed'), (6, 'Failed')], null=True)),
                ('to_address', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('tx_native_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tx_erc20_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transfers',
                'ordering': ('-created_at',),
                'managed': False,
            },
        ),
    ]
