# Generated by Django 2.2 on 2019-12-16 08:12

from django.db import migrations, models
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'New'), (2, 'Preparing'), (3, 'Prepared'), (4, 'Pending'), (5, 'Processing'), (6, 'Ready'), (7, 'Completed'), (8, 'Cancelled'), (9, 'Failed')], null=True)),
                ('input_status', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Pending'), (2, 'Active'), (3, 'Error')], null=True)),
                ('stream_contract_id', models.BigIntegerField(blank=True, null=True)),
                ('stream_contract_address', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('input_url', models.CharField(blank=True, max_length=255, null=True)),
                ('output_url', models.CharField(blank=True, max_length=255, null=True)),
                ('rtmp_url', models.CharField(blank=True, max_length=255, null=True)),
                ('refunded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'db_table': 'streams',
                'ordering': ('-created_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_id', models.IntegerField()),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('PENDING', 'PENDING'), ('ASSIGNED', 'ASSIGNED'), ('ENCODING', 'ENCODING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')], default='CREATED', max_length=30)),
                ('profile_id', models.CharField(max_length=36)),
                ('cmdline', models.TextField(blank=True, null=True)),
                ('input', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('output', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('client_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('stream_contract_id', models.BigIntegerField(blank=True, null=True)),
                ('stream_contract_address', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
    ]
